# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from constants import globalConstants as gc
import openpyxl

class TestAddToCart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.get(gc.BASE_URL)
    self.driver.set_window_size(1477, 880)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addToCart(self):
    
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "user-name")))
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "login-button")))
    self.driver.find_element(By.ID, "login-button").click()
    
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-backpack")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-bike-light")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-bike-light").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-bolt-t-shirt")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-bolt-t-shirt").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-fleece-jacket")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-fleece-jacket").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-onesie")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-onesie").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-test.allthethings()-t-shirt-(red)")))
    self.driver.find_element(By.ID, "add-to-cart-test.allthethings()-t-shirt-(red)").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]")))
    assert self.driver.find_element(By.ID, "remove-sauce-labs-backpack").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bike-light\"]")))
    assert self.driver.find_element(By.ID, "remove-sauce-labs-bike-light").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]")))
    assert self.driver.find_element(By.ID, "remove-sauce-labs-bolt-t-shirt").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-fleece-jacket\"]")))
    assert self.driver.find_element(By.ID, "remove-sauce-labs-fleece-jacket").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-onesie\"]")))
    assert self.driver.find_element(By.ID, "remove-sauce-labs-onesie").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"remove-test.allthethings()-t-shirt-(red)\"]")))
    assert self.driver.find_element(By.ID, "remove-test.allthethings()-t-shirt-(red)").text == "Remove"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".shopping_cart_link")))
    self.driver.find_element(By.CSS_SELECTOR, ".shopping_cart_link").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".title")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".title").text == "Your Cart"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name").text == "Sauce Labs Backpack"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name").text == "Sauce Labs Bike Light"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_1_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_1_title_link > .inventory_item_name").text == "Sauce Labs Bolt T-Shirt"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_5_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_5_title_link > .inventory_item_name").text == "Sauce Labs Fleece Jacket"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_2_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_2_title_link > .inventory_item_name").text == "Sauce Labs Onesie"
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#item_3_title_link > .inventory_item_name")))
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_3_title_link > .inventory_item_name").text == "Test.allTheThings() T-Shirt (Red)"
    self.driver.close()
  
