# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from constants import globalConstants as gc
import openpyxl

class TestStandarduserlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.get(gc.BASE_URL)
    self.driver.set_window_size(1477, 880)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_standarduserlogin(self):
    
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "user-name")))
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.ID, "login-button")))
    self.driver.find_element(By.ID, "login-button").click()
    self.vars["x"] = len(self.driver.find_elements(By.CSS_SELECTOR, ".inventory_item:nth-child(1) .inventory_item_desc"))
    print("{}".format(self.vars["x"]))
    self.driver.close()
  
