# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from constants import globalConstants as gc
import openpyxl

class TestblankLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  def get_Login_Data():
    pass
  
  @pytest.mark.skip()
  def test_blankLogin(self):
    
    giris_button = WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[contains(.,\'Giriş Yap\')]")))
    giris_button.click()
    warning_field = WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//p[contains(.,\'Doldurulması zorunlu alan*\')]")))
    assert warning_field.text == "Doldurulması zorunlu alan*"
    toast_message = WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "p:nth-child(4)")))
    assert toast_message.text == "Doldurulması zorunlu alan*"
    self.driver.close()
  
