# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestinvalidLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  @pytest.mark.skip()
  def test_invalidLogin(self):
    user_email = WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@name=\'email\']")))
    user_email.send_keys("icimdekisi@gmail.com")
    user_password = WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@name=\'password\']")))
    user_password.send_keys("tobetopassword")
    giris_button = WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[contains(.,\'Giriş Yap\')]")))
    giris_button.click()
    toast_message_text = WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".toast-body"))).text
   
    assert toast_message_text == "• Geçersiz e-posta veya şifre."
    
  
